sudo: false
language: python
python:
    - "2.7"
    - "2.6"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
install:
    - pip install requests hacking pytest pytest-cov
script:
    - flake8 .
    - py.test --cov --ignore=test/
    - pip install -r requirements.test.txt
deploy:
    provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    server: https://pypi.python.org/pypi
    on:
        all_branches: true
        tags: true
        python: 2.7
notifications:
    slack:
      rooms:
        - f5openstackdev:$SLACK_PROJECT_TOKEN
        - f5openstackdev:$SLACK_BUILD_STATUS_TOKEN
      on_success: change
      on_failure: always
