sudo: false
language: python
python:
    - "2.7"
    - "2.6"
before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
    - git fetch --depth=100
install:
    - pip install hacking pytest pytest-cov
script:
    - flake8 .
    - py.test --cov .
notifications:
    slack:
      rooms:
        - f5openstackdev:IbC9KXz2vGVq9jkOLCT5USYD#icontrol_rest_python
        - f5openstackdev:IbC9KXz2vGVq9jkOLCT5USYD#build-status
      on_success: change
      on_failure: always
